CREATE TABLE Customers 
(
ID INT NOT NULL AUTO_INCREMENT,
LastName VARCHAR(20) NOT NULL,
FirstName VARCHAR (20) NOT NULL,
Street VARCHAR(20) NOT NULL,
City VARCHAR(20) NOT NULL,
State VARCHAR(20) NOT NULL,
ZipCode CHAR(5) NOT NULL,
CreditCardType VARCHAR(20) NOT NULL,
CreditCardNumber CHAR(16) NOT NULL,
ExpirationDate VARCHAR(20) NOT NULL,
PurchasedProducts VARCHAR (180) NOT NULL,
PRIMARY KEY(ID)
);
